server:
  port: 9999


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cafeManagement
    username: postgres
    password: dj3306
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect







